name: Create release-branch 

on:
  repository_dispatch:
    types: [create-release-branch]
#    inputs:
#      git_ref:
#        description: 'tag, branch or commit sha which will be deployed'
#        required: true
#        type: string


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
     - env:
          MESSAGE: ${{ github.event }}
        run: echo $MESSAGE
      - env:
          MESSAGE: ${{ github.event.client_payload }}
        run: echo $MESSAGE
