name: Update release-branch description

on:
  repository_dispatch:
    types: [update-release-branch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        branch: "jira-release-num-${{github.event.client_payload.release_id}}"

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "jira-release-num-${{github.event.client_payload.release_id}}"
        destination_branch: "master"                      # If blank, default: master
        pr_body: ${{github.event.client_payload.release_notes_text}}
