name: Update release-branch description

on:
  repository_dispatch:
    types: [update-release-branch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

    - name: update-pull-request
      uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: "jira-release-num-${{github.event.client_payload.release_id}}}}"
        body-template: |
          ${{github.event.client_payload.release_notes_text}}
          Merging into '%basebranch%'
          [Link to %headbranch%](https://url/to/browse/ticket/%headbranch%)
        body-update-action: 'replace'
